# Forward Propagation

In [103]:
import numpy as np

In [104]:
x=np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
y=np.array([[0,0,0,1]]).T

In [105]:
def sigmoid(z):
    return 1/(1+np.exp(-z))    

In [106]:
def derivsigmoid(z):
    return sigmoid(z)*(1-sigmoid(z))

In [107]:
weights=2*np.random.random((3,1)) -1
weights

array([[ 0.58484297],
       [-0.27047036],
       [-0.90994273]])

In [108]:
def forward(x,weights):
    output0 = x
    input_o=np.dot(output0,weights)
    output1 = sigmoid(input_o)
    return output1

In [109]:
forward(x,weights)

array([[0.64218101],
       [0.4194334 ],
       [0.57795221],
       [0.35535783]])

In [110]:
def train(x,y,weights,lr):
    for i in range(1000):
        output0 = x
        input_o=np.dot(output0,weights)
        output1 = sigmoid(input_o)
        
        first_term=(output1-y)
        second_term=derivsigmoid(input_o)
        firsttwoterms=first_term * second_term
        changes=np.array([[0.0],[0.0],[0.0]])
        for k in range(3):
            for j in range(4):
                changes[k][0]+=firsttwoterms[j][0]*output0[j][0]
                
        weights=weights - lr * changes
        
    return weights
        
    
    

In [120]:
final_weights=train2(x,y,weights,0.2)
final_weights , forward(x,final_weights)

(array([[-5.27422863],
        [ 3.44309933],
        [ 3.44305823]]), array([[0.00509581],
        [0.1380989 ],
        [0.1381038 ],
        [0.83367902]]))

In [118]:
def train2(x,y,weights,lr):
    for i in range(1000):
        output0 = x
        input_o=np.dot(output0,weights)
        output1 = sigmoid(input_o)
        
        first_term=(output1-y)
        second_term=derivsigmoid(input_o)
        firsttwoterms=first_term * second_term
        changes=np.array([[0.0],[0.0],[0.0]])
        changes=np.dot(output0.T,firsttwoterms)
                
        weights=weights - lr * changes
        
    return weights
        
    
    