In [3]:
import math as n

In [4]:
n.sqrt(10)

3.1622776601683795

In [5]:
import numpy as np

In [18]:
a=[1,2,3,4]
ar=np.array(a, dtype='int32')

In [19]:
ar


array([1, 2, 3, 4], dtype=int32)

In [20]:
ar[0]
ar[2]

3

In [21]:
c=np.zeros(10)

In [22]:
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
ar.dtype

dtype('int32')

In [24]:
ar[0]=1243432324738769869

In [27]:
ar,c

(array([-2109021235,           2,           3,           4], dtype=int32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [28]:
ar.sum()

-2109021226

In [29]:
ar.mean()

-527255306.5

In [30]:
c.dtype

dtype('float64')

In [31]:
d=np.ones(10)

In [32]:
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
e=np.arange(1,6,1)
e

array([1, 2, 3, 4, 5])

In [34]:
e.shape

(5,)

In [35]:
e.size

5

In [36]:
a

[1, 2, 3, 4]

In [38]:
ar

array([-2109021235,           2,           3,           4], dtype=int32)

a+2

In [39]:
a+2

TypeError: can only concatenate list (not "int") to list

In [40]:
ar+2

array([-2109021233,           4,           5,           6], dtype=int32)

In [41]:
ar **2

array([-1321651671,           4,           9,          16], dtype=int32)

In [42]:
a=np.array([1,5,1,2])

In [43]:
a.mean()

2.25

In [44]:
a=np.array([0,1,2,3])

In [45]:
b=np.array([2,3,4,5])

In [46]:
a.dot(b)

26

In [47]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

In [48]:
a=np.array([2,2])

In [49]:
a

array([2, 2])

In [4]:
import pandas as pd


In [52]:
iris=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

In [53]:
iris.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [56]:
iris.columns=['pl','pw','sl','sw','type']

In [57]:
iris.columns

Index(['pl', 'pw', 'sl', 'sw', 'type'], dtype='object')

In [58]:
iris.describe()

pl          pw          sl          sw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [59]:
iris.head(10)

pl   pw   sl   sw         type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa
8  4.9  3.1  1.5  0.1  Iris-setosa
9  5.4  3.7  1.5  0.2  Iris-setosa

In [60]:
iris['pw']

0      3.0
1      3.2
2      3.1
3      3.6
4      3.9
5      3.4
6      3.4
7      2.9
8      3.1
9      3.7
10     3.4
11     3.0
12     3.0
13     4.0
14     4.4
15     3.9
16     3.5
17     3.8
18     3.8
19     3.4
20     3.7
21     3.6
22     3.3
23     3.4
24     3.0
25     3.4
26     3.5
27     3.4
28     3.2
29     3.1
      ... 
119    3.2
120    2.8
121    2.8
122    2.7
123    3.3
124    3.2
125    2.8
126    3.0
127    2.8
128    3.0
129    2.8
130    3.8
131    2.8
132    2.8
133    2.6
134    3.0
135    3.4
136    3.1
137    3.0
138    3.1
139    3.1
140    3.1
141    2.7
142    3.2
143    3.3
144    3.0
145    2.5
146    3.0
147    3.4
148    3.0
Name: pw, Length: 149, dtype: float64

In [62]:
iris[iris.columns[1]]

0      3.0
1      3.2
2      3.1
3      3.6
4      3.9
5      3.4
6      3.4
7      2.9
8      3.1
9      3.7
10     3.4
11     3.0
12     3.0
13     4.0
14     4.4
15     3.9
16     3.5
17     3.8
18     3.8
19     3.4
20     3.7
21     3.6
22     3.3
23     3.4
24     3.0
25     3.4
26     3.5
27     3.4
28     3.2
29     3.1
      ... 
119    3.2
120    2.8
121    2.8
122    2.7
123    3.3
124    3.2
125    2.8
126    3.0
127    2.8
128    3.0
129    2.8
130    3.8
131    2.8
132    2.8
133    2.6
134    3.0
135    3.4
136    3.1
137    3.0
138    3.1
139    3.1
140    3.1
141    2.7
142    3.2
143    3.3
144    3.0
145    2.5
146    3.0
147    3.4
148    3.0
Name: pw, Length: 149, dtype: float64

In [64]:
iris.pw

0      3.0
1      3.2
2      3.1
3      3.6
4      3.9
5      3.4
6      3.4
7      2.9
8      3.1
9      3.7
10     3.4
11     3.0
12     3.0
13     4.0
14     4.4
15     3.9
16     3.5
17     3.8
18     3.8
19     3.4
20     3.7
21     3.6
22     3.3
23     3.4
24     3.0
25     3.4
26     3.5
27     3.4
28     3.2
29     3.1
      ... 
119    3.2
120    2.8
121    2.8
122    2.7
123    3.3
124    3.2
125    2.8
126    3.0
127    2.8
128    3.0
129    2.8
130    3.8
131    2.8
132    2.8
133    2.6
134    3.0
135    3.4
136    3.1
137    3.0
138    3.1
139    3.1
140    3.1
141    2.7
142    3.2
143    3.3
144    3.0
145    2.5
146    3.0
147    3.4
148    3.0
Name: pw, Length: 149, dtype: float64

In [66]:
iris['pw'][2]

3.1

In [72]:
iris['pw'][2:4]=np.nan

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [70]:
iris.head()

pl   pw   sl   sw         type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  NaN  1.5  0.2  Iris-setosa
3  5.0  NaN  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [73]:
iris[['sl','pl']]

sl   pl
0    1.4  4.9
1    1.3  4.7
2    1.5  4.6
3    1.4  5.0
4    1.7  5.4
5    1.4  4.6
6    1.5  5.0
7    1.4  4.4
8    1.5  4.9
9    1.5  5.4
10   1.6  4.8
11   1.4  4.8
12   1.1  4.3
13   1.2  5.8
14   1.5  5.7
15   1.3  5.4
16   1.4  5.1
17   1.7  5.7
18   1.5  5.1
19   1.7  5.4
20   1.5  5.1
21   1.0  4.6
22   1.7  5.1
23   1.9  4.8
24   1.6  5.0
25   1.6  5.0
26   1.5  5.2
27   1.4  5.2
28   1.6  4.7
29   1.6  4.8
..   ...  ...
119  5.7  6.9
120  4.9  5.6
121  6.7  7.7
122  4.9  6.3
123  5.7  6.7
124  6.0  7.2
125  4.8  6.2
126  4.9  6.1
127  5.6  6.4
128  5.8  7.2
129  6.1  7.4
130  6.4  7.9
131  5.6  6.4
132  5.1  6.3
133  5.6  6.1
134  6.1  7.7
135  5.6  6.3
136  5.5  6.4
137  4.8  6.0
138  5.4  6.9
139  5.6  6.7
140  5.1  6.9
141  5.1  5.8
142  5.9  6.8
143  5.7  6.7
144  5.2  6.7
145  5.0  6.3
146  5.2  6.5
147  5.4  6.2
148  5.1  5.9

[149 rows x 2 columns]

In [74]:
type(iris[['sl','pl']])

pandas.core.frame.DataFrame

In [76]:
type(iris['sl'])

pandas.core.series.Series

In [77]:
iris.iloc[3:5,1:3]

pw   sl
3  NaN  1.4
4  3.9  1.7

In [78]:
iris.iloc[3:5,1:3]=np.nan

In [79]:
iris.iloc[3:5,1:3]

pw  sl
3 NaN NaN
4 NaN NaN

In [80]:
iris.describe()

pl          pw          sl          sw
count  149.000000  146.000000  147.000000  149.000000
mean     5.848322    3.041096    3.804762    1.205369
std      0.828594    0.429703    1.752076    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [86]:
iris.pw=iris.pw.fillna(iris.pw.mean())
#iris.pw.fillna(iris.pw.mean(), inplace=True)

In [85]:
iris.head()

pl        pw   sl   sw         type
0  4.9  3.000000  1.4  0.2  Iris-setosa
1  4.7  3.200000  1.3  0.2  Iris-setosa
2  4.6  3.041096  1.5  0.2  Iris-setosa
3  5.0  3.041096  NaN  0.2  Iris-setosa
4  5.4  3.041096  NaN  0.4  Iris-setosa

In [90]:
#iris.dropna()
iris.dropna(inplace=True)
iris.head()

pl        pw   sl   sw         type
0  4.9  3.000000  1.4  0.2  Iris-setosa
1  4.7  3.200000  1.3  0.2  Iris-setosa
2  4.6  3.041096  1.5  0.2  Iris-setosa
5  4.6  3.400000  1.4  0.3  Iris-setosa
6  5.0  3.400000  1.5  0.2  Iris-setosa

In [91]:
iris.reset_index(drop=True,inplace=True)

In [92]:
iris.head()

pl        pw   sl   sw         type
0  4.9  3.000000  1.4  0.2  Iris-setosa
1  4.7  3.200000  1.3  0.2  Iris-setosa
2  4.6  3.041096  1.5  0.2  Iris-setosa
3  4.6  3.400000  1.4  0.3  Iris-setosa
4  5.0  3.400000  1.5  0.2  Iris-setosa

In [97]:
iris[iris.type=='Iris-setosa']

pl        pw   sl   sw         type
0   4.9  3.000000  1.4  0.2  Iris-setosa
1   4.7  3.200000  1.3  0.2  Iris-setosa
2   4.6  3.041096  1.5  0.2  Iris-setosa
3   4.6  3.400000  1.4  0.3  Iris-setosa
4   5.0  3.400000  1.5  0.2  Iris-setosa
5   4.4  2.900000  1.4  0.2  Iris-setosa
6   4.9  3.100000  1.5  0.1  Iris-setosa
7   5.4  3.700000  1.5  0.2  Iris-setosa
8   4.8  3.400000  1.6  0.2  Iris-setosa
9   4.8  3.000000  1.4  0.1  Iris-setosa
10  4.3  3.000000  1.1  0.1  Iris-setosa
11  5.8  4.000000  1.2  0.2  Iris-setosa
12  5.7  4.400000  1.5  0.4  Iris-setosa
13  5.4  3.900000  1.3  0.4  Iris-setosa
14  5.1  3.500000  1.4  0.3  Iris-setosa
15  5.7  3.800000  1.7  0.3  Iris-setosa
16  5.1  3.800000  1.5  0.3  Iris-setosa
17  5.4  3.400000  1.7  0.2  Iris-setosa
18  5.1  3.700000  1.5  0.4  Iris-setosa
19  4.6  3.600000  1.0  0.2  Iris-setosa
20  5.1  3.300000  1.7  0.5  Iris-setosa
21  4.8  3.400000  1.9  0.2  Iris-setosa
22  5.0  3.000000  1.6  0.2  Iris-setosa
23  5.0  3.400000  1.6  0.4  Iris-setosa
24  5.2  3.500000  1.5  0.2  Iris-setosa
25  5.2  3.400000  1.4  0.2  Iris-setosa
26  4.7  3.200000  1.6  0.2  Iris-setosa
27  4.8  3.100000  1.6  0.2  Iris-setosa
28  5.4  3.400000  1.5  0.4  Iris-setosa
29  5.2  4.100000  1.5  0.1  Iris-setosa
30  5.5  4.200000  1.4  0.2  Iris-setosa
31  4.9  3.100000  1.5  0.1  Iris-setosa
32  5.0  3.200000  1.2  0.2  Iris-setosa
33  5.5  3.500000  1.3  0.2  Iris-setosa
34  4.9  3.100000  1.5  0.1  Iris-setosa
35  4.4  3.000000  1.3  0.2  Iris-setosa
36  5.1  3.400000  1.5  0.2  Iris-setosa
37  5.0  3.500000  1.3  0.3  Iris-setosa
38  4.5  2.300000  1.3  0.3  Iris-setosa
39  4.4  3.200000  1.3  0.2  Iris-setosa
40  5.0  3.500000  1.6  0.6  Iris-setosa
41  5.1  3.800000  1.9  0.4  Iris-setosa
42  4.8  3.000000  1.4  0.3  Iris-setosa
43  5.1  3.800000  1.6  0.2  Iris-setosa
44  4.6  3.200000  1.4  0.2  Iris-setosa
45  5.3  3.700000  1.5  0.2  Iris-setosa
46  5.0  3.300000  1.4  0.2  Iris-setosa

In [99]:
iris[iris.sw==0.2]

pl        pw   sl   sw         type
0   4.9  3.000000  1.4  0.2  Iris-setosa
1   4.7  3.200000  1.3  0.2  Iris-setosa
2   4.6  3.041096  1.5  0.2  Iris-setosa
4   5.0  3.400000  1.5  0.2  Iris-setosa
5   4.4  2.900000  1.4  0.2  Iris-setosa
7   5.4  3.700000  1.5  0.2  Iris-setosa
8   4.8  3.400000  1.6  0.2  Iris-setosa
11  5.8  4.000000  1.2  0.2  Iris-setosa
17  5.4  3.400000  1.7  0.2  Iris-setosa
19  4.6  3.600000  1.0  0.2  Iris-setosa
21  4.8  3.400000  1.9  0.2  Iris-setosa
22  5.0  3.000000  1.6  0.2  Iris-setosa
24  5.2  3.500000  1.5  0.2  Iris-setosa
25  5.2  3.400000  1.4  0.2  Iris-setosa
26  4.7  3.200000  1.6  0.2  Iris-setosa
27  4.8  3.100000  1.6  0.2  Iris-setosa
30  5.5  4.200000  1.4  0.2  Iris-setosa
32  5.0  3.200000  1.2  0.2  Iris-setosa
33  5.5  3.500000  1.3  0.2  Iris-setosa
35  4.4  3.000000  1.3  0.2  Iris-setosa
36  5.1  3.400000  1.5  0.2  Iris-setosa
39  4.4  3.200000  1.3  0.2  Iris-setosa
43  5.1  3.800000  1.6  0.2  Iris-setosa
44  4.6  3.200000  1.4  0.2  Iris-setosa
45  5.3  3.700000  1.5  0.2  Iris-setosa
46  5.0  3.300000  1.4  0.2  Iris-setosa

In [5]:
titanic=pd.read_csv("https://ninjasfiles.s3.amazonaws.com/attachment4870b27d69764921197f1332f41aaf1cb5b.csv")

In [101]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [102]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [103]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [104]:
del iris['pw']

In [105]:
iris.head()

pl   sl   sw         type
0  4.9  1.4  0.2  Iris-setosa
1  4.7  1.3  0.2  Iris-setosa
2  4.6  1.5  0.2  Iris-setosa
3  4.6  1.4  0.3  Iris-setosa
4  5.0  1.5  0.2  Iris-setosa

In [6]:
titanic.Cabin.fillna(0, inplace=True)

In [7]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [9]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500     0        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250     0        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500     0        S

In [10]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200